### ISSUE TITLE
Fix drag and drop handling of elements on canvas

### ISSUE THREAD

**Issue by garbast** [evoWeb/imagemap#2]
Due to having the modal dialog in top frame. The drag and drop handling is currently not working

**Comment by fuf-nf** [comment]
The script runs inside "list_frame" but the modal with the canvas is attached to the top window.
Fabric 
: fabric.window and fabric.document we can overwrite the 

fix in vanillajs:
ext/imagemap/Resources/Public/JavaScript/Editor.js:15
```
if (frameElement) { // set if not the topframe
    Fabric_min_1.window = frameElement.contentWindow.parent;
    Fabric_min_1.document = frameElement.contentWindow.parent.document;
}
```

**Comment by fuf-nf** [comment]
The script runs inside "list_frame", but the modal with the canvas is attached to the top window.
We can overwrite the references that fabric should use. (fabric.window = ..., fabric.document = ...)

fix in vanillajs:
ext/imagemap/Resources/Public/JavaScript/Editor.js:15
```
if (frameElement) {
    Fabric_min_1.window = frameElement.contentWindow.parent;
    Fabric_min_1.document = frameElement.contentWindow.parent.document;
}
```            

don't know how to change this in TypeScript.
